version: "3.8"

services:
  postgres:
    container_name: PostgresDB
    image: postgres:10.5
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: myUser!234
      POSTGRES_DB: myDatabase
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
